### Nama : Syaiful Rizal Sidiq
### NIM : A11.2021.13849

## Importing Library



In [1]:
#Mengimportkan Library 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Mengimport Dataset

In [2]:
#Menginputkan File Dataset kedalam Phyton
df = pd.read_csv('Salary Data.csv')

#Menampilkan Dataset yang telah import
df

Age  Gender Education Level                      Job Title  \
0    32.0    Male      Bachelor's              Software Engineer   
1    28.0  Female        Master's                   Data Analyst   
2    45.0    Male             PhD                 Senior Manager   
3    36.0  Female      Bachelor's                Sales Associate   
4    52.0    Male        Master's                       Director   
..    ...     ...             ...                            ...   
370  35.0  Female      Bachelor's       Senior Marketing Analyst   
371  43.0    Male        Master's         Director of Operations   
372  29.0  Female      Bachelor's         Junior Project Manager   
373  34.0    Male      Bachelor's  Senior Operations Coordinator   
374  44.0  Female             PhD        Senior Business Analyst   

     Years of Experience    Salary  
0                    5.0   90000.0  
1                    3.0   65000.0  
2                   15.0  150000.0  
3                    7.0   60000.0  
4                   20.0  200000.0  
..                   ...       ...  
370                  8.0   85000.0  
371                 19.0  170000.0  
372                  2.0   40000.0  
373                  7.0   90000.0  
374                 15.0  150000.0  

[375 rows x 6 columns]

In [3]:
# Membagi dataset menjadi 2 yakni x sebagai atribut dan y sebagai label 
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [4]:
print (x)

[[32.0 'Male' "Bachelor's" 'Software Engineer' 5.0]
 [28.0 'Female' "Master's" 'Data Analyst' 3.0]
 [45.0 'Male' 'PhD' 'Senior Manager' 15.0]
 ...
 [29.0 'Female' "Bachelor's" 'Junior Project Manager' 2.0]
 [34.0 'Male' "Bachelor's" 'Senior Operations Coordinator' 7.0]
 [44.0 'Female' 'PhD' 'Senior Business Analyst' 15.0]]


In [5]:
print (y)

[ 90000.  65000. 150000.  60000. 200000.  55000. 120000.  80000.  45000.
 110000.  75000. 140000.  65000. 130000.  40000. 125000.  90000. 115000.
  35000. 180000.  80000. 190000.  50000.  60000. 140000.  45000. 110000.
  40000. 140000.  90000. 250000.  55000.  75000.  65000. 170000.  45000.
  60000. 115000.  40000. 160000.  80000. 190000.  60000.  45000. 130000.
  40000.  75000. 180000. 120000.  35000. 130000.  85000.  60000. 200000.
  50000.  95000.  65000. 140000.  55000. 105000. 170000.  50000.  80000.
 180000.  35000.  90000. 120000.  45000.  90000. 150000.  65000.  70000.
 190000.  40000. 120000.  95000. 160000. 100000. 180000.  55000.  70000.
  80000.  30000. 250000.  40000.  95000.  45000.  80000. 135000.  55000.
 120000.  40000. 105000. 170000.  75000.  65000. 160000.  35000.  90000.
 110000.  45000.  95000. 150000.  50000.  80000. 220000.  50000.  60000.
 100000.  40000. 110000.  95000. 130000.  90000.  35000.  95000.  65000.
 170000.  45000. 120000. 100000. 180000.  50000.  8

## Mencari data yang memiliki missing values

Mencari dan menampilkan atribut atau label yang memiliki missing values sehingga dapat diperbaiki data yang memiliki missing values tersebut

In [6]:
# Menampikan Jumlah Missing values dari setiap atribut
df.isnull().sum()

Age                    2
Gender                 2
Education Level        2
Job Title              2
Years of Experience    2
Salary                 2
dtype: int64

## Memperbaiki missing value (nan)

### Membersihkan Data Non-Numerik

Metode yang digunakan yakni  imputasi most frequent atau modus untuk memperbaiki missing values pada data non-Numerik. Metode ini akan mengambil data yang sering keluar pada dataset.

###### Pertama mencari most_frequent data dari masing masing atribut yang memiliki missing values

In [7]:
most_frequent_gender = df["Gender"].mode()[0]
most_frequent_gender

'Male'

In [8]:
most_frequent_Education = df["Education Level"].mode()[0]
most_frequent_Education

"Bachelor's"

In [9]:
most_frequent_Job = df["Job Title"].mode()[0]
most_frequent_Job

'Director of Marketing'

Langkah Kedua, imputasikan data yang dihasilkan dari langkah pertama

In [10]:
df["Gender"] = df["Gender"].fillna(most_frequent_gender)
df["Education Level"] = df["Education Level"].fillna(most_frequent_Education)
df["Job Title"] = df["Job Title"].fillna(most_frequent_Job)

In [11]:
#menampilkan data atribut yang telah imputasikan 
df.isnull().sum()

Age                    2
Gender                 0
Education Level        0
Job Title              0
Years of Experience    2
Salary                 2
dtype: int64

### Membersihkan Data Numerik

Proses pembersihan data yang bersifat numerik, disini menggunakan metode imputasi menggunakan mean (nilai rata rata). Metode ini akan mengambil data dari rata-rata dari data pada atribut yang memiliki missing values yang mana nantinya akan diimputasikan pada data yang kosong di atribut yang memiliki msissing value.

Data Numerik yang memiliki missing values pada dataset tersebut yaitu pada atribut Age,Years of Experience dan salary.

In [12]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
df['Age'] = imputer.fit_transform(df[['Age']])

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
df['Years of Experience'] = imputer.fit_transform(df[['Years of Experience']])

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
df['Salary'] = imputer.fit_transform(df[['Salary']])

In [13]:
print (df)

      Age  Gender Education Level                      Job Title  \
0    32.0    Male      Bachelor's              Software Engineer   
1    28.0  Female        Master's                   Data Analyst   
2    45.0    Male             PhD                 Senior Manager   
3    36.0  Female      Bachelor's                Sales Associate   
4    52.0    Male        Master's                       Director   
..    ...     ...             ...                            ...   
370  35.0  Female      Bachelor's       Senior Marketing Analyst   
371  43.0    Male        Master's         Director of Operations   
372  29.0  Female      Bachelor's         Junior Project Manager   
373  34.0    Male      Bachelor's  Senior Operations Coordinator   
374  44.0  Female             PhD        Senior Business Analyst   

     Years of Experience    Salary  
0                    5.0   90000.0  
1                    3.0   65000.0  
2                   15.0  150000.0  
3                    7.0   60000.0 

In [14]:
#Menampilkan data atribut yang telah di imputasikan
df.isnull().sum()

Age                    0
Gender                 0
Education Level        0
Job Title              0
Years of Experience    0
Salary                 0
dtype: int64

## Encoding data kategori (Atribut)

Proses encoding bertujuan untuk mengubah nilai kategori atau string menjadi nilai numerik agar dapat digunakan dalam analisis data atau model machine learning.

Pada dataset ini saya menggunakan teknik encoding One-Hot-Encoding dimana berjalan dengan membuat variabel dummy baru untuk setiap nilai kategori unik dan mengisinya dengan 0 atau 1.

In [15]:
#mengencoding data ketegori atribut
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [16]:
print(x)

[[0.0 1.0 0.0 ... "Bachelor's" 'Software Engineer' 5.0]
 [1.0 0.0 0.0 ... "Master's" 'Data Analyst' 3.0]
 [0.0 1.0 0.0 ... 'PhD' 'Senior Manager' 15.0]
 ...
 [1.0 0.0 0.0 ... "Bachelor's" 'Junior Project Manager' 2.0]
 [0.0 1.0 0.0 ... "Bachelor's" 'Senior Operations Coordinator' 7.0]
 [1.0 0.0 0.0 ... 'PhD' 'Senior Business Analyst' 15.0]]


## Encoding data kategori (Class / Label)

Bagian ini menggunakan teknik encoding LabelEncoder, yang mana merupakan salah satu class yang dimiliki oleh library sklearn.preprocessing

In [17]:
#mengencoding data kategori label
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [18]:
print (y)

[13  8 25  7 33  6 19 11  4 17 10 23  8 21  3 20 13 18  2 30 11 32  5  7
 23  4 17  3 23 13 35  6 10  8 28  4  7 18  3 27 11 32  7  4 21  3 10 30
 19  2 21 12  7 33  5 14  8 23  6 16 28  5 11 30  2 13 19  4 13 25  8  9
 32  3 19 14 27 15 30  6  9 11  1 35  3 14  4 11 22  6 19  3 16 28 10  8
 27  2 13 17  4 14 25  5 11 34  5  7 15  3 17 14 21 13  2 14  8 28  4 19
 15 30  5 11 23  3 14 17  5 16 27  4 15 27  2  6 23  5  7 19  3 17  5 22
  3 13 25  7 11 29  4 19 23  2 14 17  5 18 31  3 13 29  4 11 19  2 17 25
  5 16 30  3 36 23  4 12 23  5 11 28  3 16 24  3 12 21 14 15 30  2 14 28
  4 14 19  3 13 26  6 17 30  4 21  4 13 27  5 19 28  3 17 25  3 12 21 15
 14 30  2 15 28  4 15 23  3 16 27  9 19 32  4 19  5 12 23  4 15 23  9 19
 27  3 19 25  9 14 30  5 14 28  3 17 25  3 12 21 15 14 30  0 36 19 27  5
 17  3 14 23  7 17 25  7 13 30  3 19 27  9 14 30  5 14 28  2 15 25  7 12
 21  8 17 30  3 13 23  7 21 27  3 15 30  6 19 25  9 14 30  5 19 28  2 15
 25  7 12 21 11 14  3 19 27  8 21 30  3 15 25  6 17

## Membagi dataset ke dalam training set dan test set

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [20]:
print (x_train)

[[1.0 0.0 0.0 ... 'PhD' 'Senior Data Engineer' 16.0]
 [1.0 0.0 0.0 ... "Master's" 'Senior Financial Analyst' 6.0]
 [0.0 1.0 0.0 ... "Bachelor's" 'Junior Developer' 1.0]
 ...
 [0.0 1.0 0.0 ... 'PhD' 'Research Director' 16.0]
 [0.0 1.0 0.0 ... "Bachelor's" 'Junior Sales Representative' 3.0]
 [0.0 1.0 0.0 ... "Master's" 'Project Engineer' 14.0]]


In [21]:
print (x_test)

[[1.0 0.0 0.0 31.0 "Bachelor's" 'Customer Service Representative' 5.0]
 [1.0 0.0 0.0 30.0 "Bachelor's" 'Junior HR Coordinator' 2.0]
 [1.0 0.0 0.0 38.0 "Bachelor's" 'Senior Project Manager' 9.0]
 [0.0 0.0 1.0 nan nan nan nan]
 [0.0 1.0 0.0 36.0 'PhD' 'Principal Scientist' 11.0]
 [0.0 1.0 0.0 34.0 "Bachelor's" 'Senior Operations Coordinator' 7.0]
 [0.0 1.0 0.0 46.0 'PhD' 'Senior Researcher' 18.0]
 [1.0 0.0 0.0 39.0 "Bachelor's" 'Senior Project Manager' 12.0]
 [1.0 0.0 0.0 38.0 "Master's" 'Digital Marketing Manager' 10.0]
 [1.0 0.0 0.0 29.0 "Bachelor's" 'Junior Recruiter' 3.0]
 [0.0 1.0 0.0 33.0 "Bachelor's" 'Junior Product Manager' 4.0]
 [0.0 1.0 0.0 29.0 "Bachelor's" 'Junior Marketing Coordinator' 2.0]
 [0.0 1.0 0.0 28.0 "Bachelor's" 'Junior Operations Analyst' 1.5]
 [1.0 0.0 0.0 33.0 "Bachelor's" 'Junior Operations Manager' 5.0]
 [0.0 1.0 0.0 29.0 "Bachelor's" 'Marketing Analyst' 2.0]
 [0.0 1.0 0.0 28.0 "Bachelor's" 'Junior Financial Analyst' 2.0]
 [0.0 1.0 0.0 36.0 "Bachelor's" 'Senio

In [22]:
print(y_train)

[27 14  3 30  3 19 28 28 26 30 21 19 16 16 27  3 17  5 17 16  8  8  4  3
 14 25 28 13 14  6 36 15  4  4  5  5 27 25 15 19  9 22 15 27 23 12 13  3
  7 19 11 13 14 12 21 17  3 13 23 13 34 11 21  8  3 13 21  7 25  2  4 14
  3 30 28  7  4  4 28 17  5  6  6 14 30  5 31 28 21 17 19 15 15 30 16  6
 27 14  4  9 17 25  6 15 23  6 14 15 10 15 19  2 14  8 19  4  2 30 18  5
 10 19 27 12 12 28 25 19  3  5 23 30 13  5 25 11 32 14 19 25 33 17 30  5
 23  9 15 12 27  2  2  8  3 30  5  8 25 25 19  5 30  8  5  7  3 13  3 16
  2  2 30  9 32 25 14  4  6 30 13  7  3  5 23 19  6 24  5 28 27  7 28 10
 14  3 11 21 23 10 17 27 17 27 23  7  7  3 11  5 14 30 15  5 12 29 30 25
  7 27  3  0  3 19 13 14 19 25  9 11 19 22 25 14 21 23 17 35 17 30 14  3
  3 12 11  2 28 27  4 13  2 20 27  3 19 17 27  4  5  7  7  2 28 35 30 14
 27 14 17  3 11  8  7  5 14 19 11 17  4 17  3 15 13 21  5 25  7 12 27 11
 14 23  9 16  3 28 27  4 21 32  4 18]


In [23]:
print (y_test)

[ 4  3 19 36 19 13 25 21 13  4  7  3  2  9  6  3 17 11 29  4 19 28  5 21
 25 33  7 30  3 25 28 30 23 28  9 14 15 21 18  3 12  5 15 13  7 23 11  2
 23 25 15 23 32  4  5  3 13  9 28 30 17 13  3 14 21 13  2  6  8  3 30 12
  7 21  1]


## Feature Scaling

In [35]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
scaled_x_train = sc.fit_transform(x_train[:, :4])
scaled_x_test = sc.transform(x_test[:, :4])

In [36]:
print (scaled_x_train)

[[ 1.08347268 -1.0762311  -0.05783149  0.91652465]
 [ 1.08347268 -1.0762311  -0.05783149 -0.62776304]
 [-0.92295821  0.92916847 -0.05783149 -1.89127116]
 ...
 [-0.92295821  0.92916847 -0.05783149  1.05691445]
 [-0.92295821  0.92916847 -0.05783149 -0.76815284]
 [-0.92295821  0.92916847 -0.05783149  0.63574507]]


In [37]:
print (scaled_x_test)

[[ 1.08347268 -1.0762311  -0.05783149 -0.90854263]
 [ 1.08347268 -1.0762311  -0.05783149 -1.04893242]
 [ 1.08347268 -1.0762311  -0.05783149  0.07418591]
 [-0.92295821 -1.0762311  17.29161647         nan]
 [-0.92295821  0.92916847 -0.05783149 -0.20659367]
 [-0.92295821  0.92916847 -0.05783149 -0.48737325]
 [-0.92295821  0.92916847 -0.05783149  1.19730424]
 [ 1.08347268 -1.0762311  -0.05783149  0.2145757 ]
 [ 1.08347268 -1.0762311  -0.05783149  0.07418591]
 [ 1.08347268 -1.0762311  -0.05783149 -1.18932221]
 [-0.92295821  0.92916847 -0.05783149 -0.62776304]
 [-0.92295821  0.92916847 -0.05783149 -1.18932221]
 [-0.92295821  0.92916847 -0.05783149 -1.329712  ]
 [ 1.08347268 -1.0762311  -0.05783149 -0.62776304]
 [-0.92295821  0.92916847 -0.05783149 -1.18932221]
 [-0.92295821  0.92916847 -0.05783149 -1.329712  ]
 [-0.92295821  0.92916847 -0.05783149 -0.20659367]
 [ 1.08347268 -1.0762311  -0.05783149  0.35496549]
 [-0.92295821  0.92916847 -0.05783149  1.47808382]
 [-0.92295821  0.92916847 -0.05