#### Nama : Syaiful Rizal Sidiq | | NIM : A11.2021.13849

#### Mengimport library numpy, pandas dan scikit-learn

In [4]:
import numpy as np
import pandas as pd
from sklearn import tree

####  Membaca Dataset Dari File ke Pandas DataFrame

In [50]:
df = pd.read_csv('car_data.csv', delimiter=",", header=0)
df.head()

User ID Gender  Age  AnnualSalary  Purchased
0      385   Male   35         20000          0
1      681   Male   40         43500          0
2      353   Male   49         74000          0
3      895   Male   40        107500          1
4      661   Male   25         79000          0

#### Mengecek atribut mana saja yang memiliki missing value

In [51]:
df.isnull().sum()

User ID         0
Gender          0
Age             0
AnnualSalary    0
Purchased       0
dtype: int64

#### Mengubah kelas (kolom "Gender") dari String ke Unique-Integer

In [52]:
df["Gender"] = pd.factorize(df.Gender)[0]

#### Menghapus kolom "User ID"

In [54]:
df = df.drop(labels="User ID", axis=1)

In [55]:
print(df)

     Gender  Age  AnnualSalary  Purchased
0         0   35         20000          0
1         0   40         43500          0
2         0   49         74000          0
3         0   40        107500          1
4         0   25         79000          0
..      ...  ...           ...        ...
995       0   38         59000          0
996       1   47         23500          0
997       1   28        138500          1
998       1   48        134000          1
999       1   44         73500          0

[1000 rows x 4 columns]


#### Mengubah dataFrame ke array Numpy

In [56]:
df = df.to_numpy()

In [57]:
# Menampilkan data
print(df)

[[     0     35  20000      0]
 [     0     40  43500      0]
 [     0     49  74000      0]
 ...
 [     1     28 138500      1]
 [     1     48 134000      1]
 [     1     44  73500      0]]


####  Membagi Dataset => 800 baris data untuk training dan 200 baris data untuk testing

In [58]:
dataTraning = np.concatenate((df[0:400, :], df[500:900, :]), axis =0)
dataTraning = np.concatenate((df[400:500, :], df[900:1000, :]), axis =0)

#### Memecah Dataset ke Input dan Label

In [59]:
inputTraining = dataTraning[:, 0:4]
inputTesting = dataTraning[:, 0:4]
labelTraining = dataTraning[:, 0]
labelTesting = dataTraning [:, 0]

#### Mendefinisikan Decision Tree Classifier

In [60]:
model = tree.DecisionTreeClassifier()

#### Mentraining Model

In [61]:
model = model.fit(inputTraining, labelTraining)

#### Memprediksi Input Data Testing

In [62]:
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya : ", labelTesting)
print("Hasil Prediksi : ", hasilPrediksi)

Label Sebenarnya :  [1 1 0 1 1 0 0 0 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 1 1 0 0 0 0 1 1 1 0 1 0
 0 1 0 1 1 1 1 0 1 0 0 1 0 0 1 0 1 0 1 1 1 0 0 0 0 1 0 1 1 1 1 1 1 0 0 1 1
 0 1 0 1 0 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 0 1 0 1 1 1 0 0 1 1 0 1 1 0 0 0 0
 1 0 1 0 1 1 1 0 1 0 0 1 1 1 1 0 1 1 0 0 0 1 1 1 1 0 1 0 1 1 0 1 0 0 1 0 0
 0 0 0 0 1 0 1 1 1 0 1 1 0 1 1 0 1 0 1 0 0 0 1 1 0 1 0 1 1 1 1 0 1 1 0 0 1
 1 0 1 0 1 0 1 1 1 1 0 1 1 1 1]
Hasil Prediksi :  [1 1 0 1 1 0 0 0 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 1 1 0 0 0 0 1 1 1 0 1 0
 0 1 0 1 1 1 1 0 1 0 0 1 0 0 1 0 1 0 1 1 1 0 0 0 0 1 0 1 1 1 1 1 1 0 0 1 1
 0 1 0 1 0 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 0 1 0 1 1 1 0 0 1 1 0 1 1 0 0 0 0
 1 0 1 0 1 1 1 0 1 0 0 1 1 1 1 0 1 1 0 0 0 1 1 1 1 0 1 0 1 1 0 1 0 0 1 0 0
 0 0 0 0 1 0 1 1 1 0 1 1 0 1 1 0 1 0 1 0 0 0 1 1 0 1 0 1 1 1 1 0 1 1 0 0 1
 1 0 1 0 1 0 1 1 1 1 0 1 1 1 1]


#### Menghitung Akurasi Data

In [63]:
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print ("Prediksi Benar : ", prediksiBenar, "data")
print ("Prediksi Salah : ", prediksiSalah, "data")
print("Akurasi : ", prediksiBenar/(prediksiBenar+prediksiSalah)*100, "%")

Prediksi Benar :  200 data
Prediksi Salah :  0 data
Akurasi :  100.0 %
